-- MySQL Script generated by MySQL Workbench
-- 04/13/16 21:13:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema results
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema results
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `results` DEFAULT CHARACTER SET latin1 ;
USE `results` ;

-- -----------------------------------------------------
-- Table `results`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `results`.`answers` (
  `group` INT(11) NOT NULL,
  `answer1` VARCHAR(100) NOT NULL,
  `answer2` VARCHAR(100) NOT NULL,
  `answer3` VARCHAR(100) NOT NULL,
  `answer4` VARCHAR(100) NOT NULL,
  `answer5` VARCHAR(100) NOT NULL,
  `correct` INT(11) NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`group`),
  UNIQUE INDEX `group_UNIQUE` (`group` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
